server:
  servlet:
    context-path: /files
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  port: ${FILE_SERVICE_PORT}
spring:
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  application:
    name: file-service

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${FILES_MONGODB_DB_NAME}

beeja:
  fileUploadLocation: ${FILE_UPLOAD_LOCATION}
  #provide localpath

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

client-urls:
  employeeService: ${EMPLOYEE_SERVICE_BASE_URL}/employees
  accountsService: ${ACCOUNTS_SERVICE_BASE_URL}/accounts
# actuator
management:
  endpoints.web.exposure.include: health,info
  info.env.enabled: true
info:
  application.name: ${spring.application.name}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    url: /openApi.yaml
file-format:
  allowedTypes:
    - application/pdf
    - application/vnd.openxmlformats-officedocument.wordprocessingml.document
    - application/msword
    - image/png
    - image/jpeg
jwt:
  secret: ${JWT_SECRET_KEY}